[CmdletBinding()]
param(
    [string]$InstallRoot = "$env:USERPROFILE\CodexMontageFF\20.2.5",
    [switch]$PreflightOnly
)
$ErrorActionPreference='Stop'; Set-StrictMode -Version Latest
if(-not [Environment]::Is64BitOperatingSystem){throw '仅支持64位Windows 10/11。'}
$source=Split-Path -Parent $MyInvocation.MyCommand.Path
$python=Join-Path $source 'runtime\python\python.exe'
if(-not(Test-Path -LiteralPath $python)){throw "随包 Python 缺失：$python"}
& $python -c "import sys; raise SystemExit(0 if sys.version_info[:3] == (3, 13, 15) and sys.maxsize > 2**32 else 1)"
if($LASTEXITCODE-ne 0){throw '随包 Python 必须是 64 位 3.13.15。'}
$ff="$source\components\ffmpeg-montage-controller\dependencies\ffmpeg\bin\ffmpeg.exe";$fp="$source\components\ffmpeg-montage-controller\dependencies\ffmpeg\bin\ffprobe.exe";$model="$source\components\ffmpeg-montage-controller\dependencies\models\models--mobiuslabsgmbh--faster-whisper-large-v3-turbo\snapshots\0a363e9161cbc7ed1431c9597a8ceaf0c4f78fcf\model.bin"
$semantic="$source\components\semantic-analysis-training-backup-v20";$renderer="$semantic\scripts\portable_frame_renderer.py";$repair="$semantic\scripts\frame_range_repair.py";$frameGate="$semantic\scripts\v20_frame_plan_gate.py";$ledger="$semantic\scripts\winky_ledger.py";$runtimeLock="$source\runtime-lock.json"
foreach($required in $ff,$fp,$model,$renderer,$repair,$frameGate,$ledger,$runtimeLock){if(-not(Test-Path -LiteralPath $required)){throw "便携依赖缺失：$required"}}
if($PreflightOnly){& $python -X utf8 "$source\tools\build_ff_suite.py" verify;if($LASTEXITCODE-ne 0){throw '组件树验证失败'};& $python -X utf8 "$source\tools\verify_suite.py";if($LASTEXITCODE-ne 0){throw '三件套验证失败'};& $python -c "import faster_whisper, onnxruntime, cv2, PIL, yaml";if($LASTEXITCODE-ne 0){throw '随包 Python 模块加载失败'};@{schema='v20-ff-deployment-preflight/v1';version='20.2.5';decision='pass';python=$python;ffmpeg=$ff;ffprobe=$fp;model=$model}|ConvertTo-Json -Depth 4;return}
$resolved=[IO.Path]::GetFullPath($InstallRoot);if($resolved.Length-gt 90){throw "安装根目录过长，会导致PyAV DLL加载失败，请改用短路径，例如 C:\CodexMontageFF\20.2.5：$resolved"};if(Test-Path -LiteralPath $resolved){throw "目标版本目录已存在，请更换InstallRoot：$resolved"};New-Item -ItemType Directory -Path $resolved -Force|Out-Null
& robocopy.exe $source $resolved /E /COPY:DAT /DCOPY:DAT /R:2 /W:1 /XD .git artifacts __pycache__ .pytest_cache /XF *.pyc 'deployment-report.json'|Out-Null;if($LASTEXITCODE-ge 8){throw "复制失败：$LASTEXITCODE"}
$installedPython=Join-Path $resolved 'runtime\python\python.exe'
& $installedPython -X utf8 "$resolved\tools\build_ff_suite.py" build|Out-Null;if($LASTEXITCODE-ne 0){throw '重建注册表失败'}
& $installedPython -X utf8 "$resolved\tools\validate_v20_release.py";if($LASTEXITCODE-ne 0){throw 'V20发布验证失败'}
$codexHome=if($env:CODEX_HOME){$env:CODEX_HOME}else{"$env:USERPROFILE\.codex"};$skills="$codexHome\skills";$officialSkills="$env:USERPROFILE\.agents\skills";New-Item -ItemType Directory -Path $skills,$officialSkills -Force|Out-Null
$installedSkillPaths=@();foreach($pair in @(@("$resolved\components\ffmpeg-montage-controller","ffmpeg-montage-controller"),@("$resolved\components\semantic-analysis-training-backup-v20","semantic-analysis-training-backup-v20"),@("$resolved\components\montage-three-part-orchestrator-ff","montage-three-part-orchestrator-ff"))){$src=$pair[0];$name=$pair[1];$dst=Join-Path $skills $name;if(Test-Path -LiteralPath $dst){$backup="$codexHome\skill-backups\$name.bak-$(Get-Date -Format yyyyMMdd-HHmmss)";New-Item -ItemType Directory -Path (Split-Path -Parent $backup)-Force|Out-Null;Move-Item -LiteralPath $dst -Destination $backup};Copy-Item -LiteralPath $src -Destination $dst -Recurse;$officialDst=Join-Path $officialSkills $name;if(Test-Path -LiteralPath $officialDst){$backup="$codexHome\skill-backups\official-$name.bak-$(Get-Date -Format yyyyMMdd-HHmmss)";New-Item -ItemType Directory -Path (Split-Path -Parent $backup)-Force|Out-Null;Move-Item -LiteralPath $officialDst -Destination $backup};try{New-Item -ItemType Junction -Path $officialDst -Target $dst -ErrorAction Stop|Out-Null}catch{Copy-Item -LiteralPath $dst -Destination $officialDst -Recurse};$installedSkillPaths+=@($dst,$officialDst)}
$active="$codexHome\three-part-suite-ff\active.json";New-Item -ItemType Directory -Path (Split-Path -Parent $active)-Force|Out-Null;@{schema='three-part-suite-ff-active/v1';suite_root=$resolved;version='20.2.5';render_mode='source_frame_ranges/v1';adjacent_same_source='coalesce_monotonic_touching_or_overlapping_frame_ranges';seconds_only_fallback=$false}|ConvertTo-Json|Set-Content -LiteralPath $active -Encoding UTF8
$installedController="$resolved\components\ffmpeg-montage-controller";$installedSemantic="$resolved\components\semantic-analysis-training-backup-v20"
$report=@{schema='v20-ff-deployment-report/v1';version='20.2.5';installed_at=(Get-Date).ToString('o');install_root=$resolved;python=$python;bundled_ffmpeg="$installedController\dependencies\ffmpeg\bin\ffmpeg.exe";bundled_ffprobe="$installedController\dependencies\ffmpeg\bin\ffprobe.exe";bundled_model="$installedController\dependencies\models\models--mobiuslabsgmbh--faster-whisper-large-v3-turbo\snapshots\0a363e9161cbc7ed1431c9597a8ceaf0c4f78fcf\model.bin";portable_renderer="$installedSemantic\scripts\portable_frame_renderer.py";frame_range_repair="$installedSemantic\scripts\frame_range_repair.py";boundary_signal_scan="$installedSemantic\scripts\v20_boundary_signal_scan.py";opening_visual_family_gate="$installedSemantic\scripts\v20_opening_visual_family_gate.py";winky_ledger="$installedSemantic\scripts\winky_ledger.py";legacy_skill_root=$skills;official_skill_root=$officialSkills;installed_skill_paths=$installedSkillPaths;render_mode='source_frame_ranges/v1';adjacent_same_source='coalesce_monotonic_touching_or_overlapping_frame_ranges';seconds_only_fallback=$false;preflight_passed=$true;restart_codex_required=$true};New-Item -ItemType Directory -Path "$resolved\artifacts" -Force|Out-Null;$report|ConvertTo-Json -Depth 5|Set-Content -LiteralPath "$resolved\artifacts\deployment-report.json" -Encoding UTF8;$report|ConvertTo-Json -Depth 5
Write-Host '部署完成。请完全退出并重新打开Codex。' -ForegroundColor Green
