[CmdletBinding()]
param(
    [string]$InstallRoot = "$env:USERPROFILE\CodexMontageFF\20.2.5",
    [switch]$InstallMissingPython,
    [switch]$PreflightOnly
)
$ErrorActionPreference='Stop'; Set-StrictMode -Version Latest
function Find-Python310 {
    $items=@("$env:LOCALAPPDATA\Programs\Python\Python310\python.exe","$env:ProgramFiles\Python310\python.exe")
    foreach($item in $items){if(Test-Path -LiteralPath $item){& $item -c "import sys;raise SystemExit(0 if sys.version_info[:2]==(3,10) else 1)";if($LASTEXITCODE-eq 0){return $item}}}
    $command=Get-Command python.exe -ErrorAction SilentlyContinue;if($command){& $command.Source -c "import sys;raise SystemExit(0 if sys.version_info[:2]==(3,10) else 1)";if($LASTEXITCODE-eq 0){return $command.Source}}
    return $null
}
if(-not [Environment]::Is64BitOperatingSystem){throw '仅支持64位Windows 10/11。'}
$source=Split-Path -Parent $MyInvocation.MyCommand.Path
$python=Find-Python310
if($null-eq $python -and $InstallMissingPython){$winget=Get-Command winget.exe -ErrorAction SilentlyContinue;if(-not $winget){throw '缺少Python 3.10且没有winget。'};& $winget.Source install --exact --id Python.Python.3.10 --accept-package-agreements --accept-source-agreements --silent;$python=Find-Python310}
if($null-eq $python){throw '缺少64位Python 3.10。'}
$ff="$source\01-FFmpeg控制器\ffmpeg-montage-controller\dependencies\ffmpeg\bin\ffmpeg.exe";$fp="$source\01-FFmpeg控制器\ffmpeg-montage-controller\dependencies\ffmpeg\bin\ffprobe.exe";$model="$source\01-FFmpeg控制器\ffmpeg-montage-controller\dependencies\models\models--mobiuslabsgmbh--faster-whisper-large-v3-turbo\snapshots\0a363e9161cbc7ed1431c9597a8ceaf0c4f78fcf\model.bin"
$semantic="$source\02-语义分析包\versions\semantic-analysis-training-backup-v20";$renderer="$semantic\scripts\portable_frame_renderer.py";$repair="$semantic\scripts\frame_range_repair.py";$frameGate="$semantic\scripts\v20_frame_plan_gate.py";$ledger="$semantic\scripts\winky_ledger.py";$runtimeLock="$source\runtime-lock.json"
foreach($required in $ff,$fp,$model,$renderer,$repair,$frameGate,$ledger,$runtimeLock){if(-not(Test-Path -LiteralPath $required)){throw "便携依赖缺失：$required"}}
if($PreflightOnly){& $python -X utf8 "$source\build_ff_suite.py" verify;if($LASTEXITCODE-ne 0){throw '组件树验证失败'};& $python -X utf8 "$source\verify_suite.py";if($LASTEXITCODE-ne 0){throw '三件套验证失败'};@{schema='v20-ff-deployment-preflight/v1';version='20.2.5';decision='pass';python=$python;ffmpeg=$ff;ffprobe=$fp;model=$model}|ConvertTo-Json -Depth 4;return}
$resolved=[IO.Path]::GetFullPath($InstallRoot);if($resolved.Length-gt 90){throw "安装根目录过长，会导致PyAV DLL加载失败，请改用短路径，例如 C:\CodexMontageFF\20.2.5：$resolved"};if(Test-Path -LiteralPath $resolved){throw "目标版本目录已存在，请更换InstallRoot：$resolved"};New-Item -ItemType Directory -Path $resolved -Force|Out-Null
& robocopy.exe $source $resolved /E /COPY:DAT /DCOPY:DAT /R:2 /W:1 /XD __pycache__ /XF *.pyc *.zip *.sha256 '部署环境报告.json'|Out-Null;if($LASTEXITCODE-ge 8){throw "复制失败：$LASTEXITCODE"}
& $python -X utf8 "$resolved\build_ff_suite.py" build|Out-Null;if($LASTEXITCODE-ne 0){throw '重建注册表失败'}
& $python -X utf8 "$resolved\validate_v20_release.py";if($LASTEXITCODE-ne 0){throw 'V20发布验证失败'}
$codexHome=if($env:CODEX_HOME){$env:CODEX_HOME}else{"$env:USERPROFILE\.codex"};$skills="$codexHome\skills";$officialSkills="$env:USERPROFILE\.agents\skills";New-Item -ItemType Directory -Path $skills,$officialSkills -Force|Out-Null
$installedSkillPaths=@();foreach($pair in @(@("$resolved\01-FFmpeg控制器\ffmpeg-montage-controller","ffmpeg-montage-controller"),@("$resolved\02-语义分析包\versions\semantic-analysis-training-backup-v20","semantic-analysis-training-backup-v20"),@("$resolved\03-完整执行器\montage-three-part-orchestrator-ff","montage-three-part-orchestrator-ff"))){$src=$pair[0];$name=$pair[1];$dst=Join-Path $skills $name;if(Test-Path -LiteralPath $dst){$backup="$codexHome\skill-backups\$name.bak-$(Get-Date -Format yyyyMMdd-HHmmss)";New-Item -ItemType Directory -Path (Split-Path -Parent $backup)-Force|Out-Null;Move-Item -LiteralPath $dst -Destination $backup};Copy-Item -LiteralPath $src -Destination $dst -Recurse;$officialDst=Join-Path $officialSkills $name;if(Test-Path -LiteralPath $officialDst){$backup="$codexHome\skill-backups\official-$name.bak-$(Get-Date -Format yyyyMMdd-HHmmss)";New-Item -ItemType Directory -Path (Split-Path -Parent $backup)-Force|Out-Null;Move-Item -LiteralPath $officialDst -Destination $backup};try{New-Item -ItemType Junction -Path $officialDst -Target $dst -ErrorAction Stop|Out-Null}catch{Copy-Item -LiteralPath $dst -Destination $officialDst -Recurse};$installedSkillPaths+=@($dst,$officialDst)}
$active="$codexHome\three-part-suite-ff\active.json";New-Item -ItemType Directory -Path (Split-Path -Parent $active)-Force|Out-Null;@{schema='three-part-suite-ff-active/v1';suite_root=$resolved;version='20.2.5';render_mode='source_frame_ranges/v1';adjacent_same_source='coalesce_monotonic_touching_or_overlapping_frame_ranges';seconds_only_fallback=$false}|ConvertTo-Json|Set-Content -LiteralPath $active -Encoding UTF8
$installedController="$resolved\01-FFmpeg控制器\ffmpeg-montage-controller";$installedSemantic="$resolved\02-语义分析包\versions\semantic-analysis-training-backup-v20"
$report=@{schema='v20-ff-deployment-report/v1';version='20.2.5';installed_at=(Get-Date).ToString('o');install_root=$resolved;python=$python;bundled_ffmpeg="$installedController\dependencies\ffmpeg\bin\ffmpeg.exe";bundled_ffprobe="$installedController\dependencies\ffmpeg\bin\ffprobe.exe";bundled_model="$installedController\dependencies\models\models--mobiuslabsgmbh--faster-whisper-large-v3-turbo\snapshots\0a363e9161cbc7ed1431c9597a8ceaf0c4f78fcf\model.bin";portable_renderer="$installedSemantic\scripts\portable_frame_renderer.py";frame_range_repair="$installedSemantic\scripts\frame_range_repair.py";boundary_signal_scan="$installedSemantic\scripts\v20_boundary_signal_scan.py";opening_visual_family_gate="$installedSemantic\scripts\v20_opening_visual_family_gate.py";winky_ledger="$installedSemantic\scripts\winky_ledger.py";legacy_skill_root=$skills;official_skill_root=$officialSkills;installed_skill_paths=$installedSkillPaths;render_mode='source_frame_ranges/v1';adjacent_same_source='coalesce_monotonic_touching_or_overlapping_frame_ranges';seconds_only_fallback=$false;preflight_passed=$true;restart_codex_required=$true};$report|ConvertTo-Json -Depth 5|Set-Content -LiteralPath "$resolved\部署环境报告.json" -Encoding UTF8;$report|ConvertTo-Json -Depth 5
Write-Host '部署完成。请完全退出并重新打开Codex。' -ForegroundColor Green
